import sys
import os
import signal
import subprocess
import time
import json
import platform
import shlex


# ============================================================
# PATHS
# ============================================================

BASE_DIR = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "..")
)

DATA_DIR = os.path.join(BASE_DIR, "data")
os.makedirs(DATA_DIR, exist_ok=True)
DB_PATH = os.path.join(DATA_DIR, "nids.db")


# ============================================================
# PID FILE
# ============================================================

PID_FILE = os.path.join(
    DATA_DIR,
    "pipeline.pid"
)


# ============================================================
# SEPARATE LOG FILES
# ============================================================

LOG_FILE_PIPELINE = os.path.join(
    DATA_DIR,
    "pipeline_manager.log"
)

LOG_FILE_CAPTURE = os.path.join(
    DATA_DIR,
    "flow_capture.log"
)

LOG_FILE_BUFFER = os.path.join(
    DATA_DIR,
    "buffer_writer.log"
)

LOG_FILE_MAIN = os.path.join(
    DATA_DIR,
    "main_processor.log"
)


# ============================================================
# INTERNAL LOG WRITER
# ============================================================

def write_pipeline_log(message):
    """
    Write messages generated by the pipeline manager itself.

    IMPORTANT:
    This file is owned only by soc_pipeline_mgr.py.
    """

    try:
        with open(
            LOG_FILE_PIPELINE,
            "a",
            encoding="utf-8"
        ) as f:

            timestamp = time.strftime(
                "%Y-%m-%d %H:%M:%S"
            )

            f.write(
                f"[{timestamp}] {message}\n"
            )

    except Exception:
        pass


# ============================================================
# CHECK PIPELINE STATUS
# ============================================================

def _read_pid_state():
    """
    PID_FILE stores JSON: {"main_pid": <int>, "buffer_pid": <int>}.
    Both PIDs must be persisted -- the buffer/capture pipeline PID was
    previously only kept in the in-process return value of start_pipeline()
    and never written to disk, so a later stop_pipeline() call (which is
    typically a *different* process invocation, e.g. from soc_server.py)
    had no way to find and kill flow-capture.exe / buffer_writer.py. That is
    the root cause of leftover capture/buffer processes surviving stop.

    A legacy PID_FILE containing a bare integer (old format, main_pid only)
    is still accepted for backward compatibility, with buffer_pid=None.
    """
    if not os.path.exists(PID_FILE):
        return None

    try:
        with open(PID_FILE, "r", encoding="utf-8") as f:
            raw = f.read().strip()

        try:
            state = json.loads(raw)
            return {
                "main_pid": state.get("main_pid"),
                "buffer_pid": state.get("buffer_pid"),
            }
        except json.JSONDecodeError:
            # Legacy format: bare PID integer
            return {"main_pid": int(raw), "buffer_pid": None}

    except Exception:
        return None


def _pid_alive(pid):
    if not pid:
        return False

    if sys.platform == "win32":
        result = subprocess.run(
            ["tasklist", "/FI", f"PID eq {pid}"],
            capture_output=True,
            text=True,
            creationflags=subprocess.CREATE_NO_WINDOW
        )
        return str(pid) in result.stdout
    else:
        try:
            os.kill(pid, 0)
            return True
        except Exception:
            return False


def is_running():

    state = _read_pid_state()
    if not state:
        return False, None

    main_pid = state.get("main_pid")
    buffer_pid = state.get("buffer_pid") 

    main_alive = _pid_alive(main_pid)
    buffer_alive = _pid_alive(buffer_pid)
    if main_alive or buffer_alive:
        return True, main_pid if main_alive else buffer_pid
    return False, None



# ============================================================
# START PIPELINE
# ============================================================

def start_pipeline(interface=None):

    running, pid = is_running()

    if running:

        write_pipeline_log(
            f"Start requested but pipeline is already running. "
            f"PID={pid}"
        )

        return {
            "status": "already_running",
            "pid": pid,
            "interface": interface
        }


    if not interface:

        write_pipeline_log(
            "Start failed: no capture interface was provided."
        )

        return {
            "status": "error",
            "error": "No capture interface was provided"
        }


    # ========================================================
    # PROJECT PATHS
    # ========================================================

    root_dir = BASE_DIR


    flow_bin = os.path.join(
        root_dir,
        "flow-capture",
        "bin",
        "flow-capture"
    )


    buffer_writer = os.path.join(
        root_dir,
        "detection-service",
        "src",
        "buffer_writer.py"
    )


    main_py = os.path.join(
        root_dir,
        "detection-service",
        "src",
        "main.py"
    )


    if sys.platform == "win32":
        flow_bin += ".exe"


    # ========================================================
    # VALIDATE FILES
    # ========================================================

    if not os.path.isfile(flow_bin):

        error = (
            f"flow-capture executable not found: "
            f"{flow_bin}"
        )

        write_pipeline_log(
            f"START ERROR: {error}"
        )

        return {
            "status": "error",
            "error": error
        }


    if not os.path.isfile(buffer_writer):

        error = (
            f"buffer_writer.py not found: "
            f"{buffer_writer}"
        )

        write_pipeline_log(
            f"START ERROR: {error}"
        )

        return {
            "status": "error",
            "error": error
        }


    if not os.path.isfile(main_py):

        error = (
            f"main.py not found: "
            f"{main_py}"
        )

        write_pipeline_log(
            f"START ERROR: {error}"
        )

        return {
            "status": "error",
            "error": error
        }


    # ========================================================
    # LOG START
    # ========================================================

    write_pipeline_log(
        "=" * 70
    )

    write_pipeline_log(
        "Starting NIDS pipeline"
    )

    write_pipeline_log(
        f"Platform: {platform.system()}"
    )

    write_pipeline_log(
        f"Capture Device: {interface}"
    )

    write_pipeline_log(
        f"Flow Capture Log: {LOG_FILE_CAPTURE}"
    )

    write_pipeline_log(
        f"Buffer Writer Log: {LOG_FILE_BUFFER}"
    )

    write_pipeline_log(
        f"Main Processor Log: {LOG_FILE_MAIN}"
    )


    # ========================================================
    # START FLOW CAPTURE + BUFFER WRITER
    # ========================================================

    #
    # IMPORTANT:
    #
    # flow-capture stdout MUST remain a PIPE because it
    # contains JSON flow records.
    #
    # flow-capture stderr goes to:
    #
    #     flow_capture.log
    #
    # buffer_writer stdout/stderr goes to:
    #
    #     buffer_writer.log
    #
    # This prevents log-file conflicts.
    #

    py_exe = sys.executable or "python"

    capture_command = (
        f'"{flow_bin}" '
        f'-i "{interface}" '
        f'-t 2'
    )

    cmd_main = f'"{py_exe}" "{main_py}" --buffer --db-path "{DB_PATH}" >> "{LOG_FILE_MAIN}" 2>&1'
    


    #
    # We need a shell pipeline:
    #
    # flow-capture.exe
    #       |
    #       v
    # buffer_writer.py
    #

    cmd_buffer = (
        f'"{flow_bin}" -i "{interface}" -t 2 2>> "{LOG_FILE_CAPTURE}" | '
        f'"{py_exe}" "{buffer_writer}" --db-path "{DB_PATH}" --interface "{interface}" >> "{LOG_FILE_BUFFER}" 2>&1'
    )

    print(
        f"[pipeline] Starting capture on: {interface}"
    )


    # ========================================================
    # START BUFFER PIPELINE
    # ========================================================

    try:

        if sys.platform == "win32":

            proc_buffer = subprocess.Popen(
                cmd_buffer,
                shell=True,
                cwd=root_dir,
                creationflags=subprocess.CREATE_NEW_PROCESS_GROUP
            )

        else:

            proc_buffer = subprocess.Popen(
                cmd_buffer,
                shell=True,
                cwd=root_dir,
                preexec_fn=os.setsid
            )

    except Exception as e:

        error = (
            f"Failed to start capture/buffer pipeline: "
            f"{e}"
        )

        write_pipeline_log(
            f"START ERROR: {error}"
        )

        return {
            "status": "error",
            "error": error
        }


    # ========================================================
    # GIVE CAPTURE A MOMENT TO START
    # ========================================================

    time.sleep(0.5)


    # ========================================================
    # START MAIN DETECTION PROCESSOR
    # ========================================================

    try:
        if sys.platform == "win32":
            proc_main = subprocess.Popen(
                cmd_main,
                shell=True,
                cwd=root_dir,
                creationflags=subprocess.CREATE_NEW_PROCESS_GROUP
            )
        else:
            proc_main = subprocess.Popen(
                cmd_main,
                shell=True,
                cwd=root_dir,
                preexec_fn=os.setsid
            )
    except Exception as e:
        error = f"Failed to start main processor: {e}"
        write_pipeline_log(f"START ERROR: {error}")
        # terminate buffer/capture pipeline
        try:
            if sys.platform == "win32":
                subprocess.run(f"taskkill /F /T /PID {proc_buffer.pid}", shell=True, capture_output=True)
            else:
                os.killpg(os.getpgid(proc_buffer.pid), signal.SIGTERM)
        except Exception:
            pass
        return {"status": "error", "error": error}


    # ========================================================
    # STORE BOTH PIDs (main processor AND capture/buffer pipeline)
    # ========================================================
    # Both PIDs are stored so stop_pipeline() can reliably terminate the
    # pipeline even when invoked from a different process than the one
    # that started it.

    with open(
        PID_FILE,
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            {
                "main_pid": proc_main.pid,
                "buffer_pid": proc_buffer.pid,
            },
            f
        )


    # ========================================================
    # WRITE PIPELINE LOG
    # ========================================================

    write_pipeline_log(
        f"Pipeline started successfully."
    )

    write_pipeline_log(
        f"Capture/Buffer Process PID: "
        f"{proc_buffer.pid}"
    )

    write_pipeline_log(
        f"Main Processor PID: "
        f"{proc_main.pid}"
    )

    write_pipeline_log(
        f"Capture Device: "
        f"{interface}"
    )

    write_pipeline_log(
        "-" * 70
    )


    return {
        "status": "started",
        "pid": proc_main.pid,
        "buffer_pid": proc_buffer.pid,
        "interface": interface
    }


# ============================================================
# STOP PIPELINE
# ============================================================

def _kill_pid_tree(pid, label):
    if not pid:
        return

    try:
        if sys.platform == "win32":
            result = subprocess.run(
                f"taskkill /F /T /PID {pid}",
                shell=True,
                capture_output=True,
                text=True
            )
            write_pipeline_log(f"taskkill ({label}) result: {result.stdout.strip()}")
            if result.stderr.strip():
                write_pipeline_log(f"taskkill ({label}) stderr: {result.stderr.strip()}")
        else:
            os.killpg(os.getpgid(pid), signal.SIGTERM)

    except Exception as e:
        write_pipeline_log(f"Primary stop method failed for {label} (PID={pid}): {e}")
        try:
            os.kill(pid, signal.SIGTERM)
        except Exception:
            pass

def _wait_for_death(pid, label, timeout_sec=5.0):
    if not pid:
        return True
    deadline = time.time() + timeout_sec
    while time.time() < deadline:
        if not _pid_alive(pid):
            return True
        time.sleep(0.2)
    write_pipeline_log(f"WARNING: {label} (PID={pid}) did not die within {timeout_sec}s")
    return False



def stop_pipeline():

    running, pid = is_running()
    state = _read_pid_state() or {}
    buffer_pid = state.get("buffer_pid")

    if not running and not _pid_alive(buffer_pid):

        write_pipeline_log(
            "Stop requested but pipeline is not running."
        )

        return {
            "status": "not_running"
        }


    write_pipeline_log(
        f"Stopping pipeline main_pid={pid} buffer_pid={buffer_pid}"
    )

    # Stop the main detection processor.
    _kill_pid_tree(pid, "main")

    # Stop the capture/buffer pipeline. This PID is now always available
    # from PID_FILE (see start_pipeline), so it is reliably terminated even
    # when stop_pipeline() runs in a different process than start_pipeline().
    _kill_pid_tree(buffer_pid, "buffer")

    _wait_for_death(pid, "main", timeout_sec=5.0)
    _wait_for_death(buffer_pid, "buffer", timeout_sec=5.0)


    # ========================================================
    # REMOVE PID FILE
    # ========================================================

    try:

        if os.path.exists(PID_FILE):
            os.remove(PID_FILE)

    except Exception as e:

        write_pipeline_log(
            f"Failed to remove PID file: {e}"
        )


    write_pipeline_log(
        "Pipeline stopped by user."
    )

    write_pipeline_log(
        "=" * 70
    )


    return {
        "status": "stopped"
    }


# ============================================================
# READ ONE LOG FILE
# ============================================================

def get_logs(
    lines=80,
    log_file=LOG_FILE_PIPELINE
):

    """
    Read the last N lines from a specific log file.
    """

    if not os.path.exists(log_file):
        return []


    try:

        with open(
            log_file,
            "r",
            encoding="utf-8",
            errors="ignore"
        ) as f:

            all_lines = [
                line.strip()
                for line in f.readlines()
                if line.strip()
            ]

            return all_lines[-lines:]

    except Exception:

        return []


# ============================================================
# READ COMBINED LOGS
# ============================================================

def get_combined_logs(lines=100):

    """
    Read logs from all pipeline components.

    Every component has its own log file.
    """

    logs = []


    log_sources = [
        ("pipeline", LOG_FILE_PIPELINE),
        ("capture", LOG_FILE_CAPTURE),
        ("buffer", LOG_FILE_BUFFER),
        ("main", LOG_FILE_MAIN),
    ]


    for name, log_file in log_sources:

        if not os.path.exists(log_file):
            continue


        try:

            with open(
                log_file,
                "r",
                encoding="utf-8",
                errors="ignore"
            ) as f:

                for line in f:

                    line = line.strip()

                    if line:

                        logs.append(
                            f"[{name}] {line}"
                        )

        except Exception:

            pass


    return logs[-lines:]


# ============================================================
# STATUS
# ============================================================

def get_status():

    running, pid = is_running()


    return {
        "is_running": running,
        "pid": pid,

        "log_file": LOG_FILE_PIPELINE,

        "logs": {
            "pipeline": LOG_FILE_PIPELINE,
            "capture": LOG_FILE_CAPTURE,
            "buffer": LOG_FILE_BUFFER,
            "main": LOG_FILE_MAIN,
        },

        "has_logs": (
            os.path.exists(LOG_FILE_PIPELINE)
            or
            os.path.exists(LOG_FILE_CAPTURE)
            or
            os.path.exists(LOG_FILE_BUFFER)
            or
            os.path.exists(LOG_FILE_MAIN)
        )
    }


# ============================================================
# CLI
# ============================================================

if __name__ == "__main__":

    action = (
        sys.argv[1]
        if len(sys.argv) > 1
        else "status"
    )


    # --------------------------------------------------------
    # STATUS
    # --------------------------------------------------------

    if action == "status":

        print(
            json.dumps(
                get_status(),
                ensure_ascii=False
            )
        )


    # --------------------------------------------------------
    # START
    # --------------------------------------------------------

    elif action == "start":

        if len(sys.argv) < 3:

            print(
                json.dumps(
                    {
                        "status": "error",
                        "error": (
                            "Capture device is required. "
                            "Example: python "
                            "soc_pipeline_mgr.py start "
                            "\"\\\\Device\\\\NPF_{GUID}\""
                        )
                    },
                    ensure_ascii=False
                )
            )

            sys.exit(1)


        interface = sys.argv[2]

        print(
            json.dumps(
                start_pipeline(interface),
                ensure_ascii=False
            )
        )


    # --------------------------------------------------------
    # STOP
    # --------------------------------------------------------

    elif action == "stop":

        print(
            json.dumps(
                stop_pipeline(),
                ensure_ascii=False
            )
        )


    # --------------------------------------------------------
    # LOGS
    # --------------------------------------------------------

    elif action == "logs":

        count = (
            int(sys.argv[2])
            if len(sys.argv) > 2
            else 50
        )

        print(
            json.dumps(
                get_logs(count),
                ensure_ascii=False
            )
        )


    # --------------------------------------------------------
    # COMBINED LOGS
    # --------------------------------------------------------

    elif action == "combined-logs":

        count = (
            int(sys.argv[2])
            if len(sys.argv) > 2
            else 100
        )

        print(
            json.dumps(
                get_combined_logs(count),
                ensure_ascii=False
            )
        )


    # --------------------------------------------------------
    # UNKNOWN COMMAND
    # --------------------------------------------------------

    else:

        print(
            json.dumps(
                {
                    "status": "error",
                    "error": f"Unknown action: {action}"
                },
                ensure_ascii=False
            )
        )

        sys.exit(1)